parameters:
    main:
         # Common hyperparameters
        simulator: 'global'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'warehouse'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 8
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'GRUPolicy'
        # learning_agent_ids: [7, 8, 9, 10, 13, 14, 15, 16, 19, 20, 21, 22, 25, 26, 27, 28]
        learning_agent_ids: [13, 14, 15, 16, 19, 20, 21, 22]
        hidden_size: 256
        hidden_size_2: 128