parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8
        num_actions: 4
        name: 'warehouse'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 8
        num_workers: 2
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'GRUPolicy'
        learning_agent_ids: [7, 9, 14, 16, 19, 21, 26, 29]
        hidden_size: 256
        hidden_size_2: 128
        influence_train_freq: 5.0e+5

    influence:
        # Common hyperparameters
        seq_len: 100
        recurrent: True
        episode_length: 100
        data_path: './influence/data/warehouse/'
        lr: 1.0e-4
        num_epochs: 200
        batch_size: 32
        hidden_memory_size: 64
        input_size: 37
        output_size: 4
        n_sources: 4
        checkpoint_path: './influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 5.0e+4