warehouse:
  n_rows: 49 # n_robots_row*(domain_size-1) + 1
  n_columns: 49 # n_robots_column*(domain_size-1) + 1
  n_robots_row: 12
  n_robots_column: 12
  distance_between_shelves: 4
  robot_domain_size: [5, 5]
  prob_item_appears: 0.02
  obs_type: 'image'
  n_steps_episode: 100
  render: True
  render_delay: 0.5
