parameters:
    main:
        # Common hyperparameters
        simulator: 'distributed'
        env: 'traffic'
        obs_size: 40
        rollout_steps: 16
        num_actions: 2
        name: 'traffic'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        learning_agent_ids: [11, 20, 13, 15]
        # learning_agent_ids: [0, 1, 2, 3, 4, 5, 6, 7] #, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
        # learning_agent_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
        # learning_agent_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]
        # learning_agent_ids: [0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12, 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25, 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38, 39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51, 52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64, 65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77, 78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90, 91,  92,  93,  94,  95,  96,  97,  98,  99]
        hidden_size: 256
        hidden_size_2: 128
        influence_train_freq: 1.0e+5
        untrained_influence: False
        eval_steps: 1.0e+3

    influence:
        # Common hyperparameters
        seq_len: 1
        recurrent: False
        episode_length: 300
        data_path: './influence/data/traffic/'
        lr: 1.0e-4
        num_epochs: 100
        batch_size: 120
        hidden_memory_size: 128
        input_size: 36
        output_size: 1
        n_sources: 4
        checkpoint_path: './influence/models/traffic/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 1.0e+4