parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'traffic'
        obs_size: 40
        rollout_steps: 64
        num_actions: 2
        name: 'traffic'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        # learning_agent_ids: [6, 7, 8, 11, 12, 13, 16, 17, 18]
        learning_agent_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
        hidden_size: 256
        hidden_size_2: 128
        influence_train_freq: 5.0e+10