parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'traffic'
        obs_size: 40
        rollout_steps: 64
        num_actions: 2
        name: 'traffic'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'GRUPolicy'
        learning_agent_ids: [6, 7, 8, 11, 12, 13, 16, 17, 18]
        hidden_size: 256
        hidden_size_2: 128
        influence_train_freq: 5.0e+5

    influence:
        # Common hyperparameters
        seq_len: 300
        recurrent: True
        episode_length: 300
        data_path: './influence/data/traffic/'
        lr: 1.0e-4
        num_epochs: 300
        batch_size: 4
        hidden_memory_size: 64
        input_size: 40
        output_size: 1
        n_sources: 4
        checkpoint_path: './influence/models/traffic/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 1.0e+4