parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'traffic'
        obs_size: 40
        rollout_steps: 64
        num_actions: 2
        name: 'traffic'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 1
        epsilon: 0.1
        beta: 0.01
        render: False
        policy: 'FNNPolicy'
        # learning_agent_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
        learning_agent_ids: [8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 22, 23, 24, 25, 26, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40]
        hidden_size: 256
        hidden_size_2: 128
        influence_train_freq: 1.0e+4

    influence:
        # Common hyperparameters
        seq_len: 1
        recurrent: False
        episode_length: 300
        data_path: './influence/data/traffic/'
        lr: 1.0e-4
        num_epochs: 500
        batch_size: 1200
        hidden_memory_size: 64
        input_size: 40
        output_size: 1
        n_sources: 4
        checkpoint_path: './influence/models/traffic/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 1.0e+4